analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

# Lint rules and documentation, see http://dart-lang.github.io/linter/lints
linter:
  rules:
  - cancel_subscriptions #Cancel instances of dart.async.StreamSubscription.
  - hash_and_equals #Always override hashCode if overriding ==.
  - iterable_contains_unrelated_type #Invocation of Iterable.contains with references of unrelated types.
  - list_remove_unrelated_type #Invocation of remove with references of unrelated types.
  - test_types_in_equals #Test type arguments in operator ==(Object other).
  - unrelated_type_equality_checks #Equality operator == invocation with references of unrelated types.
  - valid_regexps #Use valid regular expression syntax.
  - use_string_buffers #Use string buffer to compose strings.
  - unnecessary_this #Don't access members with this unless avoiding shadowing.
  - unnecessary_overrides #Don't override a method to do a super method invocation with the same parameters.
  - unnecessary_new #Unnecessary new keyword.
  - unnecessary_const #Avoid const keyword.
  - unnecessary_brace_in_string_interps #Avoid using braces in interpolation when not needed.
  - recursive_getters #Property getter recursively returns itself.
  - prefer_is_not_empty #Use isNotEmpty for Iterables and Maps.
  - prefer_is_empty #Use isEmpty for Iterables and Maps.
  - prefer_interpolation_to_compose_strings #Use interpolation to compose strings and values.
  - prefer_initializing_formals #Use initializing formals when possible.
  - prefer_contains #Use contains for List and String instances.
  - only_throw_errors #Only throw instances of classes extending either Exception or Error.
  - empty_constructor_bodies #Use ; instead of {} for empty constructor bodies.
  - empty_catches #Avoid empty catch blocks.
  - annotate_overrides #Annotate overridden members.
  - empty_statements #Avoid empty statements.

