name: injector
description: injector is a simple to use and lightweight dependency injection library for dart
version: 3.0.0
homepage: https://github.com/tappeddev/injector

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  extra_pedantic: ^4.0.0
  test: ^1.25.8

